# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-09 01:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(unique=True)),
                ('states', models.CharField(max_length=1000)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2017, 9, 9, 3, 36, 34, 682968))),
                ('cities', models.CharField(max_length=100000)),
            ],
        ),
    ]
