# Generated by Django 2.0.2 on 2018-02-16 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20180213_0449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podesavanja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxylist', models.CharField(max_length=5000)),
                ('stop', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='carmodel',
            name='lastscraped',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 16, 14, 9, 38, 500792)),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='pause',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
