# Generated by Django 2.0.2 on 2018-02-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20180216_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podesavanja',
            name='stop',
        ),
        migrations.AddField(
            model_name='podesavanja',
            name='status',
            field=models.CharField(choices=[('Start', 'Start'), ('Stop', 'Stop')], default='Start', max_length=40),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='lastscraped',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
