# Generated by Django 2.0.2 on 2018-02-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20180217_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='lastscraped',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='podesavanja',
            name='status',
            field=models.CharField(choices=[('Start', 'Start'), ('Stop', 'Stop')], max_length=40),
        ),
    ]
